import 'mobj_info.dart';

/// Immutable actor tuning shared by spawning and capability reporting.
const MobjInfo playerInfo = MobjInfo(
  id: MobjType.player,
  doomEdNum: 1,
  spawnHealth: 100,
  radius: 16,
  height: 56,
  mass: 100,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'PLAY',
  flags: MobjFlags.solid | MobjFlags.shootable | MobjFlags.dropOff,
);
const MobjInfo possessedInfo = MobjInfo(
  id: MobjType.possessed,
  doomEdNum: 3004,
  spawnHealth: 20,
  radius: 20,
  height: 56,
  mass: 100,
  speed: 8,
  reactionTime: 0,
  painChance: 200,
  damage: 3,
  spriteName: 'POSS',
  flags: MobjFlags.solid | MobjFlags.shootable | MobjFlags.countKill,
);
const MobjInfo shotguyInfo = MobjInfo(
  id: MobjType.shotguy,
  doomEdNum: 9,
  spawnHealth: 30,
  radius: 20,
  height: 56,
  mass: 100,
  speed: 8,
  reactionTime: 0,
  painChance: 170,
  damage: 3,
  spriteName: 'SPOS',
  flags: MobjFlags.solid | MobjFlags.shootable | MobjFlags.countKill,
);
const MobjInfo impInfo = MobjInfo(
  id: MobjType.troop,
  doomEdNum: 3001,
  spawnHealth: 60,
  radius: 20,
  height: 56,
  mass: 100,
  speed: 8,
  reactionTime: 0,
  painChance: 200,
  damage: 3,
  spriteName: 'TROO',
  flags: MobjFlags.solid | MobjFlags.shootable | MobjFlags.countKill,
);
const MobjInfo demonInfo = MobjInfo(
  id: MobjType.sergeant,
  doomEdNum: 3002,
  spawnHealth: 150,
  radius: 30,
  height: 56,
  mass: 400,
  speed: 10,
  reactionTime: 8,
  painChance: 180,
  damage: 0,
  spriteName: 'SARG',
  flags: MobjFlags.solid | MobjFlags.shootable | MobjFlags.countKill,
  seeSound: 'DSSGTSIT',
  attackSound: 'DSSGTATK',
  painSound: 'DSDMPAIN',
  deathSound: 'DSSGTDTH',
  activeSound: 'DSDMACT',
);
const MobjInfo spectreInfo = MobjInfo(
  id: MobjType.spectre,
  doomEdNum: 58,
  spawnHealth: 150,
  radius: 30,
  height: 56,
  mass: 400,
  speed: 10,
  reactionTime: 8,
  painChance: 180,
  damage: 0,
  spriteName: 'SARG',
  flags:
      MobjFlags.solid |
      MobjFlags.shootable |
      MobjFlags.shadow |
      MobjFlags.countKill,
  seeSound: 'DSSGTSIT',
  attackSound: 'DSSGTATK',
  painSound: 'DSDMPAIN',
  deathSound: 'DSSGTDTH',
  activeSound: 'DSDMACT',
);
const MobjInfo baronInfo = MobjInfo(
  id: MobjType.baron,
  doomEdNum: 3003,
  spawnHealth: 1000,
  radius: 24,
  height: 64,
  mass: 1000,
  speed: 8,
  reactionTime: 8,
  painChance: 50,
  damage: 0,
  spriteName: 'BOSS',
  flags: MobjFlags.solid | MobjFlags.shootable | MobjFlags.countKill,
  seeSound: 'DSBRSSIT',
  attackSound: 'DSCLAW',
  painSound: 'DSDMPAIN',
  deathSound: 'DSBRSDTH',
  activeSound: 'DSDMACT',
);
const MobjInfo impShotInfo = MobjInfo(
  id: MobjType.troopshot,
  doomEdNum: -1,
  spawnHealth: 1,
  radius: 6,
  height: 8,
  mass: 100,
  speed: 10,
  reactionTime: 0,
  painChance: 0,
  damage: 3,
  spriteName: 'BAL1',
  flags: MobjFlags.missile,
);
const MobjInfo playerRocketInfo = MobjInfo(
  id: MobjType.playerRocket,
  doomEdNum: -1,
  spawnHealth: 1,
  radius: 11,
  height: 8,
  mass: 100,
  speed: 20,
  reactionTime: 0,
  painChance: 0,
  damage: 20,
  spriteName: 'MISL',
  flags: MobjFlags.missile | MobjFlags.noGravity | MobjFlags.dropOff,
);
const MobjInfo baronShotInfo = MobjInfo(
  id: MobjType.baronShot,
  doomEdNum: -1,
  spawnHealth: 1,
  radius: 6,
  height: 8,
  mass: 100,
  speed: 15,
  reactionTime: 0,
  painChance: 0,
  damage: 8,
  spriteName: 'BAL7',
  flags:
      MobjFlags.noBlockmap |
      MobjFlags.missile |
      MobjFlags.dropOff |
      MobjFlags.noGravity,
  seeSound: 'DSFIRSHT',
  deathSound: 'DSFIRXPL',
);
const MobjInfo puffInfo = MobjInfo(
  id: MobjType.puff,
  doomEdNum: -1,
  spawnHealth: 1,
  radius: 0,
  height: 0,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'PUFF',
  flags: MobjFlags.noSector | MobjFlags.noBlockmap | MobjFlags.noGravity,
);
const MobjInfo bloodInfo = MobjInfo(
  id: MobjType.blood,
  doomEdNum: -1,
  spawnHealth: 1,
  radius: 0,
  height: 0,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'BLUD',
  flags: MobjFlags.noSector | MobjFlags.noBlockmap | MobjFlags.noGravity,
);
const MobjInfo teleportFogInfo = MobjInfo(
  id: MobjType.teleportFog,
  doomEdNum: -1,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'TFOG',
  flags: MobjFlags.noBlockmap | MobjFlags.noGravity,
);
const MobjInfo teleportSpotInfo = MobjInfo(
  id: MobjType.teleportSpot,
  doomEdNum: 14,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'TFOG',
  flags: MobjFlags.noSector | MobjFlags.noBlockmap,
);
const MobjInfo tallRedTorchInfo = MobjInfo(
  id: MobjType.tallRedTorch,
  doomEdNum: 46,
  spawnHealth: 1000,
  radius: 16,
  height: 64,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'TRED',
  flags: MobjFlags.solid,
);
const MobjInfo clipInfo = MobjInfo(
  id: MobjType.clip,
  doomEdNum: 2007,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'CLIP',
  flags: MobjFlags.special,
);
const MobjInfo shotgunInfo = MobjInfo(
  id: MobjType.shotgun,
  doomEdNum: 2001,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'SHOT',
  flags: MobjFlags.special,
);
const MobjInfo chaingunInfo = MobjInfo(
  id: MobjType.chaingun,
  doomEdNum: 2002,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'MGUN',
  flags: MobjFlags.special,
);
const MobjInfo healthInfo = MobjInfo(
  id: MobjType.misc1,
  doomEdNum: 2011,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'STIM',
  flags: MobjFlags.special,
);
const MobjInfo armorInfo = MobjInfo(
  id: MobjType.misc0,
  doomEdNum: 2018,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'ARM1',
  flags: MobjFlags.special,
);
const MobjInfo blueKeyInfo = MobjInfo(
  id: MobjType.misc2,
  doomEdNum: 5,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'BKEY',
  flags: MobjFlags.special,
);
const MobjInfo yellowKeyInfo = MobjInfo(
  id: MobjType.misc3,
  doomEdNum: 6,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'YKEY',
  flags: MobjFlags.special,
);
const MobjInfo redKeyInfo = MobjInfo(
  id: MobjType.misc4,
  doomEdNum: 13,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'RKEY',
  flags: MobjFlags.special,
);
const MobjInfo healthBonusInfo = MobjInfo(
  id: MobjType.misc10,
  doomEdNum: 2014,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'BON1',
  flags: MobjFlags.special | MobjFlags.countItem,
);
const MobjInfo medikitInfo = MobjInfo(
  id: MobjType.misc12,
  doomEdNum: 2012,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'MEDI',
  flags: MobjFlags.special,
);
const MobjInfo armorBonusInfo = MobjInfo(
  id: MobjType.misc11,
  doomEdNum: 2015,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'BON2',
  flags: MobjFlags.special | MobjFlags.countItem,
);
const MobjInfo shellsInfo = MobjInfo(
  id: MobjType.misc17,
  doomEdNum: 2008,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'SHEL',
  flags: MobjFlags.special,
);
const MobjInfo soulSphereInfo = MobjInfo(
  id: MobjType.soulSphere,
  doomEdNum: 2013,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'SOUL',
  flags: MobjFlags.special | MobjFlags.countItem,
);
const MobjInfo megaSphereInfo = MobjInfo(
  id: MobjType.megaSphere,
  doomEdNum: 83,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'MEGA',
  flags: MobjFlags.special | MobjFlags.countItem,
);
const MobjInfo backpackInfo = MobjInfo(
  id: MobjType.backpack,
  doomEdNum: 8,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'BPAK',
  flags: MobjFlags.special,
);
const MobjInfo invulnerabilityInfo = MobjInfo(
  id: MobjType.invulnerability,
  doomEdNum: 2022,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'PINV',
  flags: MobjFlags.special | MobjFlags.countItem,
);
const MobjInfo berserkInfo = MobjInfo(
  id: MobjType.berserk,
  doomEdNum: 2023,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'PSTR',
  flags: MobjFlags.special | MobjFlags.countItem,
);
const MobjInfo invisibilityInfo = MobjInfo(
  id: MobjType.invisibility,
  doomEdNum: 2024,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'PINS',
  flags: MobjFlags.special | MobjFlags.countItem,
);
const MobjInfo radiationSuitInfo = MobjInfo(
  id: MobjType.radiationSuit,
  doomEdNum: 2025,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'SUIT',
  flags: MobjFlags.special,
);
const MobjInfo computerMapInfo = MobjInfo(
  id: MobjType.computerMap,
  doomEdNum: 2026,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'PMAP',
  flags: MobjFlags.special | MobjFlags.countItem,
);
const MobjInfo lightAmplificationInfo = MobjInfo(
  id: MobjType.lightAmplification,
  doomEdNum: 2045,
  spawnHealth: 1,
  radius: 20,
  height: 16,
  mass: 0,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'PVIS',
  flags: MobjFlags.special | MobjFlags.countItem,
);
const MobjInfo barrelInfo = MobjInfo(
  id: MobjType.barrel,
  doomEdNum: 2035,
  spawnHealth: 20,
  radius: 10,
  height: 42,
  mass: 100,
  speed: 0,
  reactionTime: 0,
  painChance: 0,
  damage: 0,
  spriteName: 'BAR1',
  flags: MobjFlags.solid | MobjFlags.shootable | MobjFlags.noBlood,
);
const MobjInfo floorLampInfo = MobjInfo(
  id: MobjType.misc31,
  doomEdNum: 2028,
  spawnHealth: 1000,
  radius: 16,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'COLU',
  flags: MobjFlags.solid,
);
const MobjInfo techPillarInfo = MobjInfo(
  id: MobjType.misc48,
  doomEdNum: 48,
  spawnHealth: 1000,
  radius: 16,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'ELEC',
  flags: MobjFlags.solid,
);
const MobjInfo candleInfo = MobjInfo(
  id: MobjType.misc49,
  doomEdNum: 34,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'CAND',
  flags: 0,
);
const MobjInfo candelabraInfo = MobjInfo(
  id: MobjType.misc50,
  doomEdNum: 35,
  spawnHealth: 1000,
  radius: 16,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'CBRA',
  flags: MobjFlags.solid,
);
const MobjInfo deadPlayerInfo = MobjInfo(
  id: MobjType.misc62,
  doomEdNum: 15,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'PLAY',
  flags: 0,
);
const MobjInfo deadZombieInfo = MobjInfo(
  id: MobjType.misc63,
  doomEdNum: 18,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'POSS',
  flags: 0,
);
const MobjInfo deadDemonInfo = MobjInfo(
  id: MobjType.misc64,
  doomEdNum: 21,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'SARG',
  flags: 0,
);
const MobjInfo deadImpInfo = MobjInfo(
  id: MobjType.misc66,
  doomEdNum: 20,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'TROO',
  flags: 0,
);
const MobjInfo deadShotgunGuyInfo = MobjInfo(
  id: MobjType.misc67,
  doomEdNum: 19,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'SPOS',
  flags: 0,
);
const MobjInfo bloodyMess1Info = MobjInfo(
  id: MobjType.misc68,
  doomEdNum: 10,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'PLAY',
  flags: 0,
);
const MobjInfo bloodyMess2Info = MobjInfo(
  id: MobjType.misc69,
  doomEdNum: 12,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'PLAY',
  flags: 0,
);
const MobjInfo bloodyPoolInfo = MobjInfo(
  id: MobjType.bloodyPool,
  doomEdNum: 24,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'POL5',
  flags: 0,
);
const MobjInfo rocketLauncherInfo = MobjInfo(
  id: MobjType.rocketLauncher,
  doomEdNum: 2003,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'LAUN',
  flags: MobjFlags.special,
);
const MobjInfo megaArmorInfo = MobjInfo(
  id: MobjType.megaArmor,
  doomEdNum: 2019,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'ARM2',
  flags: MobjFlags.special,
);
const MobjInfo rocketBoxInfo = MobjInfo(
  id: MobjType.rocketBox,
  doomEdNum: 2046,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'BROK',
  flags: MobjFlags.special,
);
const MobjInfo chainsawInfo = MobjInfo(
  id: MobjType.chainsaw,
  doomEdNum: 2005,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'CSAW',
  flags: MobjFlags.special,
);
const MobjInfo rocketAmmoInfo = MobjInfo(
  id: MobjType.rocketAmmo,
  doomEdNum: 2010,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'ROCK',
  flags: MobjFlags.special,
);
const MobjInfo bulletBoxInfo = MobjInfo(
  id: MobjType.bulletBox,
  doomEdNum: 2048,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'AMMO',
  flags: MobjFlags.special,
);
const MobjInfo shellBoxInfo = MobjInfo(
  id: MobjType.shellBox,
  doomEdNum: 2049,
  spawnHealth: 1000,
  radius: 20,
  height: 16,
  mass: 100,
  speed: 0,
  reactionTime: 8,
  painChance: 0,
  damage: 0,
  spriteName: 'SBOX',
  flags: MobjFlags.special,
);
MobjInfo? infoForEdNum(int n) => switch (n) {
  1 => playerInfo,
  14 => teleportSpotInfo,
  46 => tallRedTorchInfo,
  3004 => possessedInfo,
  9 => shotguyInfo,
  3001 => impInfo,
  3002 => demonInfo,
  3003 => baronInfo,
  58 => spectreInfo,
  2007 => clipInfo,
  2001 => shotgunInfo,
  2002 => chaingunInfo,
  2011 => healthInfo,
  2018 => armorInfo,
  5 => blueKeyInfo,
  6 => yellowKeyInfo,
  13 => redKeyInfo,
  2014 => healthBonusInfo,
  2012 => medikitInfo,
  2015 => armorBonusInfo,
  2008 => shellsInfo,
  2013 => soulSphereInfo,
  83 => megaSphereInfo,
  8 => backpackInfo,
  2022 => invulnerabilityInfo,
  2023 => berserkInfo,
  2024 => invisibilityInfo,
  2025 => radiationSuitInfo,
  2026 => computerMapInfo,
  2045 => lightAmplificationInfo,
  2035 => barrelInfo,
  2028 => floorLampInfo,
  48 => techPillarInfo,
  34 => candleInfo,
  35 => candelabraInfo,
  15 => deadPlayerInfo,
  18 => deadZombieInfo,
  21 => deadDemonInfo,
  20 => deadImpInfo,
  19 => deadShotgunGuyInfo,
  10 => bloodyMess1Info,
  12 => bloodyMess2Info,
  24 => bloodyPoolInfo,
  2003 => rocketLauncherInfo,
  2005 => chainsawInfo,
  2019 => megaArmorInfo,
  2046 => rocketBoxInfo,
  2010 => rocketAmmoInfo,
  2048 => bulletBoxInfo,
  2049 => shellBoxInfo,
  _ => null,
};
